using DevExpress.XtraEditors;
using DropboxITX;
using Main.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Main.Forms
{
    public partial class frm_PickupCapture : DevExpress.XtraEditors.XtraForm
    {
        public GrainLoadPickup newentry { get; set;}
        public string filename { get; set; }
        public Image myImage = null;
        public frm_PickupCapture()
        {
            InitializeComponent();
            splashScreenManager1.ShowWaitForm();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_Drivers.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_Customers.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_GrainType.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_PickupLocations.Fill();
            splashScreenManager1.CloseWaitForm();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_PickupLocations.FillAsync();
        }
        private void pictureEdit1_DoubleClick(object sender, EventArgs e)
        {
            //openImageViewer
        }
        private void btn_SavePickup_Click(object sender, EventArgs e)
        {
            newentry = new GrainLoadPickup();
            newentry.release = edt_release.Text;
            newentry.factura = edt_factura.Text;
            newentry.id_driver = (Guid)lue_driver.EditValue;
            newentry.driverName = (string)lue_driver.Text;
            newentry.pickup_date = (DateTime)dte_Pickup.EditValue;
            newentry.id_customer = (Guid)lue_customer.EditValue;
            newentry.customer = (string)lue_customer.Text;
            newentry.pickup_ticket = edt_pickupticket.Text;
            newentry.id_pickup_location = (Guid)lue_locationPickup.EditValue;
            newentry.Description_Pickup_Location = (string)lue_locationPickup.Text;
            newentry.id_grainType = (Guid)lue_GrainType.EditValue;
            newentry.name_graintype = (string)lue_GrainType.Text;
            newentry.gross_pickup = Convert.ToInt32( edt_grossPickup.Text);
            newentry.tare_pickup = Convert.ToInt32(edt_tarePickup.Text);
            newentry.neto_pickup = Convert.ToInt32(edt_netoPickup.Text);
            newentry.regdate = DateTime.Now;
            newentry.id_who =Guid.Parse(Properties.Settings.Default.Id_who);
            this.DialogResult=DialogResult.OK;
            this.Close();
        }

        private void btn_CancelPickup_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
            this.Close();
        }
        private void frm_PickupCapture_Load(object sender, EventArgs e)
        {

        }

        private void btn_pickupDropbox_Click(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                filename = ofd.FileName;
                DropITX.DownloadImageMS("intelogix Dispatch/Commodities/TEST-Sistemas", edt_release.Text.ToString(), out myImage);
                pictureEdit1.Image = myImage;
            }
        }
    }
}